# Generated by Django 5.0.2 on 2024-02-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_delete_userweather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
